"""DeliveryPartner change

Revision ID: 55b65b9a363e
Revises: 47e052f428f1
Create Date: 2026-02-17 13:03:00.326852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b65b9a363e'
down_revision: Union[str, Sequence[str], None] = '47e052f428f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('delivery_prtner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['delivery_prtner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'delivery_prtner_id')
    # ### end Alembic commands ###
