"""add: destination field in shipment table

Revision ID: 8c13ab1ec9c1
Revises: 0f4e46915f7d
Create Date: 2026-02-18 11:50:53.820512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c13ab1ec9c1'
down_revision: Union[str, Sequence[str], None] = '0f4e46915f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('destination', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'destination')
    # ### end Alembic commands ###
